### ISSUE TITLE
create abstract class for CONVERTER

### ISSUE THREAD

**Issue by timpauli** [mutwo-org/mutwo#10]
within the new package mutwo.converters.abc

**Comment by timpauli** [comment]
name 
> converter
open for discussion

**Comment by timpauli** [comment]
do we always convert to some kind of file?

**Comment by levinericzimmermann** [comment]
I don't think so, it could also happen that you want to convert data to Streams (for instance MidiStream or OSCStream that send data to Supercollider or your DAW) and there may be converters that return python objects that belong to other libraries (for instance abjad data or music21 data).

If those categories share enough functionality, we could think about implementing abstract classes:

1. FileConverter
2. StreamConverter
3. PythonConverter

**Comment by levinericzimmermann** [comment]
(perhaps it could even happen that you would like to convert mutwo events to different or even the same mutwo event types with different values, e.g. converting Video-data to musical data and upside down or converting musical data that is suitable for notation to musical data that is suitable for midi output (where articulations and playing indicator become applied, for instance a staccato makes the note values shorter or a tremolo splits the tone in many smaller events))

**Comment by levinericzimmermann** [comment]
4. ParameterConverter

**Comment by levinericzimmermann** [comment]
@timpauli I suggest the module structure:

mutwo.converters.BACKEND_NAME, e.g.

-  mutwo.converters.reaper
    -  mutwo.converters.reaper.constants
    -  mutwo.converters.reaper.ReaperTrackConverter
-  mutwo.converters.mutwo
    -  mutwo.converters.mutwo.TempoConverter
-  mutwo.converters.abjad
    -  mutwo.converters.abjad.AbjadVoiceConverter
    - mutwo.converters.abjad.constants
-  mutwo.converters.midi
...

do you agree with this structure?
