### ISSUE TITLE
create abstract class for PARAMETER

### ISSUE THREAD

**Issue by levinericzimmermann** [mutwo-org/mutwo#11]
within the new package mutwo.parameters.abc

is there any functionality that unifies all parameters?

**Comment by timpauli** [comment]
i dont know. an empty class seems a bit unnecessary

**Comment by levinericzimmermann** [comment]
The abstract base class has been removed with commit 1bd0c314f28f55040715a8f2221d4c28a5cabed0

Initially I had the idea that an abstract base class Parameter may be helpful for type hints. For now it is never used, therefore I removed the class. Because it is only an empty class it would be easy to reimplement it, if it turns out that it is actually useful.
