### ISSUE TITLE
how to handle constants

### ISSUE THREAD

**Issue by levinericzimmermann** [mutwo-org/mutwo#12]
Sometimes it can be useful to have a certain set of predefined global variables, for instance when thinking of

- Western or other traditions of pitch naming and tuning and concert pitch
- Instruments and their predefined behavior (tuning, range, monophonic or not, decaying vs. sustaining)

do we want to add a specific submodule for constants of any type or shall constants be added to their respective class?

**Comment by timpauli** [comment]
extra constant submodule at local correct place at the respective class with CAPSLOCK NAMES
