### ISSUE TITLE
duration

### ISSUE THREAD

**Issue by timpauli** [mutwo-org/mutwo#3]
how do we handle the parameter duration?

possible ideas:
- duration is a seperate class?
- duration is Union[float, integer, fraction]?

**Comment by timpauli** [comment]
since we are going for implicit design it looks like `Duration = typing.Union[typing.Union[int, float], fractions.Fraction]`
or even just `numbers.Number`?

**Comment by levinericzimmermann** [comment]
duration has had been defined in mutwo.parameters.durations.abc.DurationType:
`DurationType = typing.Union[numbers.Number, Duration]`
