### ISSUE TITLE
tests structure

### ISSUE THREAD

**Issue by timpauli** [mutwo-org/mutwo#5]
see 32a5d79bd40517dbe5a953f98db38880ea8b8243

is it a good idea to mirror the structure of the mutwo package in the tests folder? @levinericzimmermann

**Comment by levinericzimmermann** [comment]
what would be the advantage in doing so?

**Comment by timpauli** [comment]
what is the advantage of structuring the main package into subpackages?
you can find stuff more easily (hopefully)
I think it is a good idea! (for the unitests as well)

I mean you never want to import the unittests as a user of the lib.
But as the library grows and grows it makes also sense for us (creators) to know quickly where to look for a specific test
