### ISSUE TITLE
ComplexEvent.duration.setter

### ISSUE THREAD

**Issue by timpauli** [mutwo-org/mutwo#6]
see 32a5d79bd40517dbe5a953f98db38880ea8b8243

the duration setter method implemented in ComplexEvent does not work in the tests (of SequentialEvent and SimultaneousEvent).
You get `AttributeError: can't set attribute`

**Comment by levinericzimmermann** [comment]
This has had been solved with commit 16d1b5801c62aa7e65b350d55e2eafcdcd0dfdb6
