### ISSUE TITLE
max line length

### ISSUE THREAD

**Issue by levinericzimmermann** [mutwo-org/mutwo#7]
What is the max line length that shall be allowed (style wise)? Blacks default are 88 characters

**Comment by timpauli** [comment]
for my personal taste 88 is a bit short.
but I would just keep at 88 because it is easier to setup for any possible contributors

@levinericzimmermann close if you agree

**Comment by levinericzimmermann** [comment]
max line length has been added to [style guide](https://github.com/mutwo-org/mutwo/wiki/style-guide)
