### ISSUE TITLE
again: import style policy

### ISSUE THREAD

**Issue by levinericzimmermann** [mutwo-org/mutwo#8]
1. maybe we should try to keep alphabetic order?
2. @timpauli do you think it is a good idea to differentiate between build-in-libraries, dependencies, and mutwo - imports, e.g.:

```python3
# build in libraries
import functools
import collections

# third party libraries
import essentia
import librosa

# import mutwo
from mutwo.events import basic
```

**Comment by timpauli** [comment]
I think we should just follow the [pep8-guidelines regarding imports](https://www.python.org/dev/peps/pep-0008/#imports)
yes, alphabetic order!
regarding grouping the guidelines state:
> Imports should be grouped in the following order:
> 
> 1. Standard library imports.
> 2. Related third party imports.
> 3. Local application/library specific imports.
> 
> You should put a blank line between each group of imports.

PyCharm offers a function called `Optimize Imports` which automatically enforces these guidelines.
@levinericzimmermann close if you agree

**Comment by levinericzimmermann** [comment]
import order has been added to [style guide](https://github.com/mutwo-org/mutwo/wiki/style-guide)
