### ISSUE TITLE
general design philosophy: implicit vs. explicit

### ISSUE THREAD

**Issue by levinericzimmermann** [mutwo-org/mutwo#9]
## implicit vs. explicit

Various issues and discussions (for instance [issue #2](https://github.com/mutwo-org/mutwo/issues/2), [issue #3](https://github.com/mutwo-org/mutwo/issues/3) and also [issue #4](https://github.com/mutwo-org/mutwo/issues/4)) deal with a more broad design philosophy decision if objects to deal with shall be implemented explicitly (class Rest, class Tone vs. class Chord, class Duration) or if it's sufficient for mutwo to understand the meaning of objects due to context (any number that is assigned to the Duration property will be understood as the objects duration, if a NoteLike object has several pitches, it is probably a chord, if a NoteLike object only has one pitch it's obviously only a Note).

We should be aware of the bigger context and when making a decision we should keep consistent throughout the package.

Personally I would prefer if the user can stay implicit as long as she or he desires, but with the possibility to move towards an explicit representation if desired. For instance when thinking about parameters:

- let's say we have a pitch. If our pitch is only a number it is uncertain if this number represents the frequency, the midi pitch or the frequency ratio.
- let's say we have a duration. if our duration is only a number it is uncertain if this number represents seconds, miliseconds, beats or midi ticks

#### Staying implicit
We could just leave it to the Converter routine to make the interpretation of the number (a routine that converts to traditional notation will understand duration as beats and a routine that converts to csound will understand duration as seconds).
In this case it should always be well documented in the Converter routine how parameters will be interpreted.

Otherwise we could define for every parameter a basic interpretation e.g. a number that has been assigned to a pitch property will always be understood as frequency and a number that has been assigned to a duration property will always be understood as seconds.

#### Becoming explicit
Furthermore when the user desires to move to an explicit representation mutwo could offer various classes for parameters that consist of different properties for the different interpretations, e.g. a pitch class would have a property for frequency, midi-pitch, frequency ratio and a duration class would have a property for seconds, beats, miliseconds, ...

**Comment by timpauli** [comment]
we agreed on staying implicit. this library should be more of a friendly helper than a system which enforces laws on you

**Comment by levinericzimmermann** [comment]
In the current implementation *mutwo* chooses a mixed solution depending on the subject:

## Events
- The generic, implicit compound events `SequentialEvent` and `SimultaneousEvent` seem to be sufficient until now.
- Rests are indeed defined as any event that gets ignored by a converter class (usually the event gets ignored if the converter class can't extract the necessary information from the event due to an attribute error).
- For making concrete useful `SimpleEvent` the user can inherit from `events.basic.SimpleEvent` (get explicit) or simply attach attributes to a `SimpleEvent` on the fly (e.g. `my_simple_event.my_attribute = 100`). 
- For now **no converter class expects any special SimpleEvent class**, they only check the attributes and if the event owns the asked attributes it will be converted (duck typing!). This saying, it is also true that the default values of converter classes often expect attribute names as they are set in the `NoteLike` class.

## Parameters
Predefined parameters are mostly explicit:
- For any common parameter besides `duration` mutwo offers abstract base classes (e.g. `mutwo.parameters.abc.Pitch` or `mutwo.parameters.abc.Volume`). If converters make use of any predefined parameter they will usually expect any object that inherits from the respective abstract base class. Users can make use of predefined classes or write their own classes through inheriting from abstract base classes. Each parameter class is essentially defined through the hopefully best "neutral" technical value with which it could be described (e.g. `frequency` for `Pitch` or `amplitude` for `Volume`). If a user simply wants to interact via this technical values, mutwo offers `Direct` classes e.g. `DirectPitch` or `DirectVolume` that simply expects the essential value during initialization.
- `duration` can be any number (float, int, fractions.Fraction). It is up to the converter how this number will be read (seconds for `CsoundScoreConverter`, beats for `MidiFileConverter` or `SequentialEventToAbjadVoiceConverter`). The reason for this inconsistency lies in the decision to separate the `duration` attribute from tempo envelopes (for a better user experience) and the out of this decision following difficulty to calculate seconds from beats and upside down within a theoretical `Duration` object.


## conclusion

=> for now the workflow is to keep implicit as long as it makes sense, but to choose explicit implementations if they bring bigger advance
